### ISSUE TITLE
When using extend react object assign is missing.

### ISSUE THREAD

**Issue by poeticninja** [ericclemmons/eslint-config-future#1]
Looks like object-assign needs to be a regular dependency and not dev for extending the react options.

**Comment by iam4x** [comment]
Ran into the same issue `Uncaught Error: Cannot find module 'object-assign'
Referenced from: /Users/iam4x/savemysmartphone/si-front-users/.eslintrc`

**Comment by ericclemmons** [comment]
Agh!  I didn't tag & release the fix.  BRB!

**Comment by ericclemmons** [comment]
@poeticninja & @iam4x `v1.1.1` should fix this!!111!!

**Comment by iam4x** [comment]
Cool thank's :+1:

**Comment by ericclemmons** [comment]
My bad!
